### ISSUE TITLE
Plugin Crashes

### ISSUE THREAD

**Issue by eyeruham** [sonburn/symbol-swapper#18] opened 2018-08-03 09:36 UTC
In the new version, the plugin crashes. 

To reproduce: 

1. Open Symbol Swapper
2. Symbol Swap Libraries
3. Select a Library and try to swap to another
4. Click 'Swap' 

Result: plugin crashes. Sometimes this even happens in between step 3 and step 4

**Comment by sonburn** [comment] 2018-08-03 15:03
@eyeruham What is your Sketch version and can you confirm your plugin version?

**Comment by sonburn** [comment] 2018-08-03 15:04
@eyeruham Can you also do the following to help me figure out whats going on?

1.	Open Utilities > Console.app
2.	Expand ~/Library/Logs in the left window, and select com.bohemiancoding.sketch3
3.	Run the plugin in Sketch, if there was an error it will appear in the right window of Console, in a file called Plugin Output.log. (If there was already a Plugin Output.log file, select it and select Clear in the action menu first).
4.	Copy/paste the output here

**Comment by eyeruham** [comment] 2018-08-03 15:05
@sonburn we are experiencing the issue on Symbol Swapper 0.12 and on both Sketch 51.1 and 51.2

**Comment by sonburn** [comment] 2018-08-03 15:07
If your log result is similar to https://github.com/sonburn/symbol-swapper/issues/12#issuecomment-410157619, then at least we know the issue is related.

**Comment by eyeruham** [comment] 2018-08-03 15:10
TypeError: alertWindow.buttons is not a function. (In 'alertWindow.buttons()', 'alertWindow.buttons' is undefined)
line: 518
sourceURL: /Users/Eyal/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Symbol Swapper.sketchplugin/Contents/Sketch/script.cocoascript
column: 24
stack: comboBoxSelectionDidChange:@/Users/Eyal/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Symbol Swapper.sketchplugin/Contents/Sketch/script.cocoascript:518:24
dynamicHandler@/Users/Eyal/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Symbol Swapper.sketchplugin/Contents/Sketch/script.cocoascript:37:32

[native code]
swapLibrary@/Users/Eyal/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Symbol Swapper.sketchplugin/Contents/Sketch/script.cocoascript:304:42
 «Plugin Output»
TypeError: alertWindow.buttons is not a function. (In 'alertWindow.buttons()', 'alertWindow.buttons' is undefined)
line: 518
sourceURL: /Users/Eyal/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Symbol Swapper.sketchplugin/Contents/Sketch/script.cocoascript
column: 24
stack: comboBoxSelectionDidChange:@/Users/Eyal/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Symbol Swapper.sketchplugin/Contents/Sketch/script.cocoascript:518:24
dynamicHandler@/Users/Eyal/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Symbol Swapper.sketchplugin/Contents/Sketch/script.cocoascript:37:32

[native code]
swapLibrary@/Users/Eyal/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Symbol Swapper.sketchplugin/Contents/Sketch/script.cocoascript:304:42
 «Plugin Output»
TypeError: alertWindow.buttons is not a function. (In 'alertWindow.buttons()', 'alertWindow.buttons' is undefined)
line: 518
sourceURL: /Users/Eyal/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Symbol Swapper.sketchplugin/Contents/Sketch/script.cocoascript
column: 24
stack: comboBoxSelectionDidChange:@/Users/Eyal/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Symbol Swapper.sketchplugin/Contents/Sketch/script.cocoascript:518:24
dynamicHandler@/Users/Eyal/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Symbol Swapper.sketchplugin/Contents/Sketch/script.cocoascript:37:32

[native code]
swapLibrary@/Users/Eyal/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Symbol Swapper.sketchplugin/Contents/Sketch/script.cocoascript:304:42
 «Plugin Output»
TypeError: alertWindow.buttons is not a function. (In 'alertWindow.buttons()', 'alertWindow.buttons' is undefined)
line: 518
sourceURL: /Users/Eyal/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Symbol Swapper.sketchplugin/Contents/Sketch/script.cocoascript
column: 24
stack: comboBoxSelectionDidChange:@/Users/Eyal/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Symbol Swapper.sketchplugin/Contents/Sketch/script.cocoascript:518:24
dynamicHandler@/Users/Eyal/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Symbol Swapper.sketchplugin/Contents/Sketch/script.cocoascript:37:32

[native code]
swapLibrary@/Users/Eyal/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Symbol Swapper.sketchplugin/Contents/Sketch/script.cocoascript:304:42
 «Plugin Output»

**Comment by sonburn** [comment] 2018-08-03 15:50
@eyeruham What version of Mac are you on? You weren't having an issue before version 0.12?

**Comment by eyeruham** [comment] 2018-08-03 15:58
10.13.6 and I didn't have any issue on previous version

**Comment by sonburn** [comment] 2018-08-03 16:47
@eyeruham Can you try this version and let me know if it works for you?

https://www.dropbox.com/sh/2358pw7fo3bpjio/AAA93OZqBMo6N41bUkZisA7za?dl=0

**Comment by sonburn** [comment] 2018-08-03 18:54
@eyeruham I've gone ahead and pushed the fix, as there is no harm either way and I believe it would solve your issue. Please check out version 0.13 which should show up as an update in Sketch. I will take down the link above.

**Comment by eyeruham** [comment] 2018-08-03 19:10
That resolved the issue, thanks a lot @sonburn!

**Closed** 2018-08-03 19:10 UTC
Labels: bug
